### ISSUE TITLE
Best way to read from multiple PLCs 

### ISSUE THREAD

**Issue by sklr** [netsmarttech/node-red-contrib-s7#64]
Hello,
I have a network of two s7 PLCs with almost identical programs. My goal is to read single variables from both PLCs then do math with them. 
Is there any way to read multiple PLCs and get the results from all in a single node?

Currently I read from both PLCs to flow variables then with a third node chain I check if the values are timed correctly and do the math. I check the reading times to be sure that there is no reading error with some PLC.

**Comment by gfcittolin** [comment]
Unfortunately there's no way of reading multiple PLCs from a single node. I think the strategy you're currently employing is the best to solve this kind of problem. The only thing I can think of is to use the status node to detect reading error or connection issues instead of timing, but that may also depend on your use case.
